version: '3.9'
services:
  proxy:
    build: .
    ports:
      - 2999:2999
      - 8000:8000
      - 1239:1239
      - 3000:3000
      - 3001:3001
    volumes:
      - c:\Users\Afonso\Desktop\ThesisCode:/code
    command: bash -c "stunnel > stunnel.txt & cd /code/PT/target && java -jar proxy-jar-with-dependencies.jar pt-proxy & sleep 3 && tor"

    