version: '3.9'
services:
  proxy:
    hostname: proxycont
    build: .
    ports:
      - 2999:2999
      - 8000:8000
    volumes:
      - c:\Users\Afonso\Desktop\ThesisCode:/code
    command: bash -c "cd /code/PT/target && java -jar proxy-jar-with-dependencies.jar proxy-pt"
    depends_on:
      - stunnel 
  
  tor:
    hostname: torcont
    build: ./Tor
    command: bash -c "tor"
    depends_on:
      - proxy 
  
  stunnel:
    hostname: stunnelcont
    build: ./Stunnel
    ports:
      - 1239:1239
      - 3000:3000
      - 3001:3001
    command: bash -c "stunnel"
    