version: '3.9'
services:
  httpserver:
    build: .
    ports:
      - 5001:5001
      - 1238:1238
      - 2238:2238
    volumes:
      - c:\Users\Afonso\Desktop\ThesisCode:/code
    command: bash -c "cd /code/HttpServer/target && java -jar httpserver-jar-with-dependencies.jar"