version: '3.9'
services:    
  bridge:
    build: .
    ports:
      - 8000:8000
    volumes:
      - c:\Users\Afonso\Desktop\ThesisCode:/code
    command: bash -c "cd /code/PT/target && mvn clean compile assembly:single && java -jar proxy-jar-with-dependencies.jar pt-server"
    depends_on: 
      - stunnel
    
  stunnel:
    hostname: stunnelcont
    build: ./Stunnel
    ports:
      - 9999:9999
    command: bash -c "stunnel"
