version: '3.9'
services:    
  tor:
    hostname: torcont
    build: ./Tor
    ports:
      - 65300:65300
      - 9051:9051
    command: bash -c "tor"
  bridge:
    build: .
    ports:
      - 8000:8000
      - 65300:65300
      - 9999:9999
    volumes:
      - c:\Users\Afonso\Desktop\ThesisCode:/code
    command: bash -c "stunnel && cd /code/PT/target && java -jar proxy-jar-with-dependencies.jar pt-server"
  