version: '3.9'
services:    
  bridge:
    build: .
    ports:
      - 8000:8000
      - 65300:65300
      - 9999:9999
    volumes:
      - c:\Users\Afonso\Desktop\ThesisCode:/code
    command: bash -c "stunnel > stunnel.txt & tor > tor.txt & cd /code/PT/target && java -jar proxy-jar-with-dependencies.jar pt-server"
    

