version: '3.9'
services:    
  bridge:
    build: .
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - /home/jvilalonga1/ThesisCode:/code
    command: bash -c "cp /code/Deployment/Setup/Bridge1/config.properties /code/PT/Config/config.properties &&
                        cp /code/Deployment/Setup/Bridge1/WebRTC/configB.js /code/PT/WebRTC/Bridge/public/config/config.js &&
                        cp /code/Deployment/Setup/Bridge1/WebRTC/default.json /code/PT/WebRTC/Signalling/config/default.json &&
                        stunnel > stunnel.txt & 
                        tor > tor.txt & 
                        cd /code/PT/target && 
                        java -jar proxy-jar-with-dependencies.jar pt-server"
    
