version: '3.9'
services:
  proxy:
    build: .
    ports:
      - 30000:30000
      - 30001:30001
      - 30002:30002
      - 30003:30004
      - 30004:30005
    volumes:
      - /home/bcarvalho1/ThesisCode:/code
    command: bash -c "cp /code/Deployment/Setup1/Proxy/config.properties /code/PT/Config/config.properties &&
                      cp /code/Deployment/Setup1/Proxy/WebRTC/configB.js /code/PT/WebRTC/Bridge/public/config/config.js &&
                      cp /code/Deployment/Setup1/Proxy/WebRTC/configC.js /code/PT/WebRTC/Client/public/config/config.js &&
                      cp /code/Deployment/Setup1/Bridge/WebRTC/default.json /code/PT/WebRTC/Signalling/config/default.json &&
                      stunnel > stunnel.txt & 
                      cd /code/PT/target && 
                      java -jar proxy-jar-with-dependencies.jar pt-proxy & 
                      sleep 3 && 
                      tor"

    