version: '3.9'
services:
  chaffclient:
    build: .
    volumes:
      - C:\Users\Afonso\Desktop\ThesisCode:/code
    command: bash -c "cp /code/Deployment/SetupAV/ChaffClient/config.properties /code/PT/Config/config.properties &&
                      cp /code/Deployment/SetupAV/ChaffClient/WebRTC/configC.js /code/PT/WebRTC/Client/public/config/config.js &&
                      cd /code/PT/target && 
                      java -jar proxy-jar-with-dependencies.jar pt-client &
                      sleep 3 &&
                      tor &
                      cd /code/Client/target && 
                      java -jar client-1.0-SNAPSHOT-jar-with-dependencies.jar chaff"
                    

                    