version: '3.9'
services:    
  bridge:
    build: .
    ports:
      - 40000:40000
      - 40001:40001
      - 40002:40002
    volumes:
      - /home/jvilalonga1/ThesisCode:/code
    command: bash -c "cp /code/Deployment/SetupHJ/Bridge4/config.properties /code/PT/Config/config.properties &&
                        cp /code/Deployment/SetupHJ/Bridge4/WebRTC/configB.js /code/PT/WebRTC/Bridge/public/config/config.js &&
                        cp /code/Deployment/SetupHJ/Bridge4/WebRTC/default.json /code/PT/WebRTC/Signalling/config/default.json &&
                        stunnel > stunnel.txt & 
                        tor > tor.txt & 
                        cd /code/PT/target && 
                        java -jar proxy-jar-with-dependencies.jar pt-server"
    
