version: '3.9'
services:
  proxy:
    ports:
      - 1234:1234
      - 10012:10012
    build: .
    volumes:
      - /home/afonso/Desktop/ThesisCode:/code
    command: bash -c "cp /code/Deployment/Setup/LocalTirClientForProxy1/config.properties /code/PT/Config/config.properties &&
                      cp /code/Deployment/Setup/LocalTirClientForProxy1/WebRTC/configC.js /code/PT/WebRTC/Client/public/config/config.js &&
                      cp /code/Deployment/Setup/LocalTirClientForProxy1/network /code/PT/Config/network &&
                      cd /code/PT/target && 
                      java -jar proxy-jar-with-dependencies.jar proxy-client"
